ui:
  port: ""
  image: icr.io/ai-services-cicd/catalog-ui:v0.0.1

backend:
  port: ""
  image: icr.io/ai-services-cicd/ai-services:0.0.2
  runtime: ""
  adminPasswordHash: ""
  podman:
    uri: "/run/podman/podman.sock"

db:
  port: ""
  image: icr.io/ai-services-private/postgres:18
  user: "admin"
  database: "postgres"
  password: ""
  dataPath: "/var/lib/ai-services/db"
  resources:
    requests:
      memory: "512Mi"
    limits:
      memory: "1Gi"
