package models

import (
	"database/sql"
	"time"
)

// BundleStatus represents the lifecycle status of an uploaded catalog bundle.
type BundleStatus string

const (
	BundleStatusProcessing BundleStatus = "processing"
	BundleStatusActive     BundleStatus = "active"
	BundleStatusFailed     BundleStatus = "failed"
)

// Bundle represents a customer-uploaded catalog bundle record in the database.
type Bundle struct {
	// ID is the UUID primary key, generated by the DB via gen_random_uuid().
	ID string `json:"id"`
	// Name is the human-readable display label from metadata.yaml `name:` field.
	// e.g. "My Custom Service", "My Custom LLM Provider". Nullable — may be empty
	// when the uploader omitted the name field.
	Name sql.NullString `json:"name"`
	// DirName is the server-determined on-disk directory name: meta.DirName().
	// Services:   <id>-<version>                       e.g. "my-service-1.0.0"
	// Components: <component_type>-<id>-<version>       e.g. "llm-my-provider-1.0.0"
	DirName string `json:"dir_name"`
	// Status tracks the lifecycle: processing → active on success, failed on error.
	Status BundleStatus `json:"status"`
	// SizeBytes is the uncompressed on-disk size in bytes; nil until extraction completes.
	SizeBytes sql.NullInt64 `json:"size_bytes"`
	// CatalogType is "service" or "component".
	CatalogType string `json:"catalog_type"`
	// CatalogID is the unique identity of the catalog item within its type.
	// Services:   bare id                              e.g. "my-service"
	// Components: composite <component_type>:<id>      e.g. "llm:my-provider"
	CatalogID string `json:"catalog_id"`
	// Version is the semantic version of this bundle, e.g. "1.0.0".
	Version string `json:"version"`
	// Error holds the validation error message when status is "failed".
	Error sql.NullString `json:"error,omitempty"`
	// UploadedBy is the user ID who uploaded this bundle.
	UploadedBy string `json:"uploaded_by"`
	// UploadedAt is the timestamp when the bundle was first recorded.
	UploadedAt time.Time `json:"uploaded_at"`
}
