-- +goose Up
-- +goose StatementBegin
CREATE TYPE bundle_status AS ENUM (
    'processing',
    'active',
    'failed',
    'deleting'
);

CREATE TABLE catalog_bundles (
    -- UUID generated by the DB via gen_random_uuid() — never supplied by the client.
    id               UUID           PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Human-readable display label from metadata.yaml `name:` field.
    -- e.g. "My Custom Service", "My Custom LLM Provider"
    -- Not required to be unique — the same label may appear for different catalog_ids.
    name             VARCHAR(255),

    status           bundle_status  NOT NULL DEFAULT 'processing',
    -- Uncompressed on-disk size in bytes, populated after extraction completes.
    -- NULL until the bundle reaches 'active', 'failed', or 'deleting'.
    size_bytes       BIGINT,

    -- The catalog item type: "service" or "component".
    catalog_type     VARCHAR(50)    NOT NULL,

    -- Unique identity of the catalog item within its type.
    -- Services:   bare id                               e.g. "my-service"
    -- Components: composite <component_type>--<id>      e.g. "llm--my-provider"
    catalog_id       VARCHAR(200)   NOT NULL,

    -- Semantic version of this bundle: e.g. "1.0.0", "2.1.0"
    version          VARCHAR(50)    NOT NULL DEFAULT '',

    error            TEXT,
    created_by       VARCHAR(100),
    created_at       TIMESTAMPTZ    NOT NULL DEFAULT NOW()
);

-- Enforce at most one active bundle per (catalog_type, catalog_id) pair.
-- Using the composite key makes the constraint explicit and future-proof:
-- a new catalog_type with the same catalog_id string as an existing one
-- is correctly treated as a distinct item.
-- 'processing', 'failed', and 'deleting' rows are exempt so a replacement in-flight
-- does not block itself.
CREATE UNIQUE INDEX uq_catalog_bundles_active
    ON catalog_bundles (catalog_type, catalog_id)
    WHERE status = 'active';
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP INDEX  IF EXISTS uq_catalog_bundles_active;
DROP TABLE  IF EXISTS catalog_bundles;
DROP TYPE   IF EXISTS bundle_status;
-- +goose StatementEnd
