package repository

import (
	"context"
	"fmt"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/project-ai-services/ai-services/internal/pkg/catalog/db/models"
)

// BundleRepository defines the interface for catalog_bundles data operations.
type BundleRepository interface {
	// Insert creates a new bundle record with status 'processing'.
	Insert(ctx context.Context, bundle *models.Bundle) error

	// GetByID returns the bundle with the given internal ID, or nil if not found.
	GetByID(ctx context.Context, id string) (*models.Bundle, error)

	// ActiveCatalogIDExists returns true if any active bundle row with the given
	// catalog_type + catalog_id combination exists.
	ActiveCatalogIDExists(ctx context.Context, catalogType, catalogID string) (bool, error)

	// ListAll returns all bundle records ordered by created_at descending.
	ListAll(ctx context.Context) ([]models.Bundle, error)

	// MarkProcessing sets the bundle status to 'processing' and clears any prior error.
	MarkProcessing(ctx context.Context, id string) error

	// MarkDeleting sets the bundle status to 'deleting' and clears any prior error.
	MarkDeleting(ctx context.Context, id string) error

	// MarkFailed sets the bundle status to 'failed' and stores the error message.
	MarkFailed(ctx context.Context, id, errorMessage string) error

	// Activate sets the bundle to status='active' and updates version, name,
	// and size_bytes in a single statement. Used by both POST and PUT after successful extraction.
	// updated_at is maintained automatically by the set_updated_at DB trigger on every UPDATE.
	Activate(ctx context.Context, id, version, displayName string, sizeBytes int64) error

	// Delete removes the bundle record by internal ID.
	Delete(ctx context.Context, id string) error
}

// bundleRepo implements BundleRepository using pgx.
type bundleRepo struct {
	pool *pgxpool.Pool
}

// NewBundleRepository creates a new BundleRepository backed by the given connection pool.
func NewBundleRepository(pool *pgxpool.Pool) BundleRepository {
	return &bundleRepo{pool: pool}
}

// Insert creates a new catalog_bundles row with status 'processing'.
// The id is generated by the DB (gen_random_uuid()); it is written back into bundle.ID.
func (r *bundleRepo) Insert(ctx context.Context, bundle *models.Bundle) error {
	query := `
		INSERT INTO catalog_bundles
			(name, status, catalog_type, catalog_id, version, created_by)
		VALUES
			($1, 'processing', $2, $3, $4, $5)
		RETURNING id, created_at, updated_at
	`

	err := r.pool.QueryRow(ctx, query,
		bundle.Name,
		bundle.CatalogType,
		bundle.CatalogID,
		bundle.Version,
		bundle.CreatedBy,
	).Scan(&bundle.ID, &bundle.CreatedAt, &bundle.UpdatedAt)
	if err != nil {
		return fmt.Errorf("failed to insert catalog bundle: %w", err)
	}

	bundle.Status = models.BundleStatusProcessing

	return nil
}

// GetByID returns the bundle record with the given ID, or nil if not found.
func (r *bundleRepo) GetByID(ctx context.Context, id string) (*models.Bundle, error) {
	query := `
		SELECT id, name, status, size_bytes, catalog_type, catalog_id, version, error, created_by, created_at, updated_at
		FROM catalog_bundles
		WHERE id = $1
	`

	bundle := &models.Bundle{}

	err := r.pool.QueryRow(ctx, query, id).Scan(
		&bundle.ID,
		&bundle.Name,
		&bundle.Status,
		&bundle.SizeBytes,
		&bundle.CatalogType,
		&bundle.CatalogID,
		&bundle.Version,
		&bundle.Error,
		&bundle.CreatedBy,
		&bundle.CreatedAt,
		&bundle.UpdatedAt,
	)
	if err != nil {
		if isNoRows(err) {
			return nil, nil
		}

		return nil, fmt.Errorf("failed to get catalog bundle by id: %w", err)
	}

	return bundle, nil
}

// ActiveCatalogIDExists returns true if an active bundle with the given catalog_type
// and catalog_id already exists.
func (r *bundleRepo) ActiveCatalogIDExists(ctx context.Context, catalogType, catalogID string) (bool, error) {
	query := `
		SELECT EXISTS(
			SELECT 1 FROM catalog_bundles
			WHERE catalog_type = $1 AND catalog_id = $2 AND status = 'active'
		)
	`

	var exists bool

	if err := r.pool.QueryRow(ctx, query, catalogType, catalogID).Scan(&exists); err != nil {
		return false, fmt.Errorf("failed to check catalog_id existence: %w", err)
	}

	return exists, nil
}

// ListAll returns all bundle records ordered by created_at descending.
func (r *bundleRepo) ListAll(ctx context.Context) ([]models.Bundle, error) {
	query := `
		SELECT id, name, status, size_bytes, catalog_type, catalog_id, version, error, created_by, created_at, updated_at
		FROM catalog_bundles
		ORDER BY created_at DESC
	`

	rows, err := r.pool.Query(ctx, query)
	if err != nil {
		return nil, fmt.Errorf("failed to list catalog bundles: %w", err)
	}
	defer rows.Close()

	var bundles []models.Bundle

	for rows.Next() {
		var b models.Bundle
		if err := rows.Scan(
			&b.ID,
			&b.Name,
			&b.Status,
			&b.SizeBytes,
			&b.CatalogType,
			&b.CatalogID,
			&b.Version,
			&b.Error,
			&b.CreatedBy,
			&b.CreatedAt,
			&b.UpdatedAt,
		); err != nil {
			return nil, fmt.Errorf("failed to scan catalog bundle: %w", err)
		}

		bundles = append(bundles, b)
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("error iterating catalog bundles: %w", err)
	}

	return bundles, nil
}

// MarkProcessing sets a bundle to status='processing' and clears any prior error.
func (r *bundleRepo) MarkProcessing(ctx context.Context, id string) error {
	_, err := r.pool.Exec(ctx, `UPDATE catalog_bundles SET status = 'processing', error = NULL WHERE id = $1`, id)
	if err != nil {
		return fmt.Errorf("failed to mark bundle processing: %w", err)
	}

	return nil
}

// MarkDeleting sets a bundle to status='deleting' and clears any prior error.
func (r *bundleRepo) MarkDeleting(ctx context.Context, id string) error {
	_, err := r.pool.Exec(ctx, `UPDATE catalog_bundles SET status = 'deleting', error = NULL WHERE id = $1`, id)
	if err != nil {
		return fmt.Errorf("failed to mark bundle deleting: %w", err)
	}

	return nil
}

// MarkFailed sets a bundle to status='failed' and stores the error message.
func (r *bundleRepo) MarkFailed(ctx context.Context, id, errorMessage string) error {
	_, err := r.pool.Exec(ctx, `UPDATE catalog_bundles SET status = 'failed', error = $1 WHERE id = $2`, errorMessage, id)
	if err != nil {
		return fmt.Errorf("failed to mark bundle failed: %w", err)
	}

	return nil
}

// Activate sets a bundle to status='active' and updates version, name, size_bytes, and clears
// any prior error in a single statement. updated_at is maintained automatically by the
// set_updated_at DB trigger — the application never writes it explicitly.
func (r *bundleRepo) Activate(ctx context.Context, id, version, displayName string, sizeBytes int64) error {
	query := `
		UPDATE catalog_bundles
		SET status = 'active', version = $1, name = $2, size_bytes = $3, error = NULL
		WHERE id = $4
	`

	_, err := r.pool.Exec(ctx, query, version, displayName, sizeBytes, id)
	if err != nil {
		return fmt.Errorf("failed to activate bundle: %w", err)
	}

	return nil
}

// Delete removes the bundle record by internal ID.
func (r *bundleRepo) Delete(ctx context.Context, id string) error {
	_, err := r.pool.Exec(ctx, `DELETE FROM catalog_bundles WHERE id = $1`, id)
	if err != nil {
		return fmt.Errorf("failed to delete catalog bundle: %w", err)
	}

	return nil
}

// isNoRows reports whether the error represents a "no rows" condition.
func isNoRows(err error) bool {
	return err == pgx.ErrNoRows
}
